### ISSUE TITLE
Nse python not working for last few days

### ISSUE THREAD

**Issue by SMVSKN** [aeron7/nsepython#50]
Hi,
my code which was running previously is failing for the last few days. Appreciate if you can help. As an example, when I run the following commands from debug promp, I get an error.

**nsepython.nse_holidays()**

Traceback (most recent call last):
  File "/home/analog/.local/lib/python3.9/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
  File "/usr/lib/python3/dist-packages/simplejson/scanner.py", line 79, in scan_once
    return _scan_once(string, idx)
  File "/usr/lib/python3/dist-packages/simplejson/scanner.py", line 70, in _scan_once
    raise JSONDecodeError(errmsg, string, idx)
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/analog/.local/lib/python3.9/site-packages/nsepython/rahu.py", line 36, in nsefetch
    output = requests.get(payload,headers=headers).json()
  File "/home/analog/.local/lib/python3.9/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/analog/.local/lib/python3.9/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
  File "/usr/lib/python3/dist-packages/simplejson/scanner.py", line 79, in scan_once
    return _scan_once(string, idx)
  File "/usr/lib/python3/dist-packages/simplejson/scanner.py", line 70, in _scan_once
    raise JSONDecodeError(errmsg, string, idx)
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/analog/.local/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3251, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-95490cee037a>", line 1, in <module>
    nsepython.nse_holidays()
  File "/home/analog/.local/lib/python3.9/site-packages/nsepython/rahu.py", line 359, in nse_holidays
    payload = nsefetch('https://www.nseindia.com/api/holiday-master?type=trading')
  File "/home/analog/.local/lib/python3.9/site-packages/nsepython/rahu.py", line 41, in nsefetch
    output = s.get(payload,headers=headers).json()
  File "/home/analog/.local/lib/python3.9/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by arpithahgowda** [comment]
Seeing same issue with nse_expirydetails(payload,0). It wasworking till tuesday.

**Comment by hitkarsh-singh** [comment]
can anyone suggest alternative for nse python equity history ? some other wrapper opensource library or api?

**Comment by aeron7** [comment]
Use https://forum.unofficed.com/ to address.
